name: Persubmit Checks
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:

  build_and_test_gpu_windows:
    name: Build and Test (Windows GPU)
    runs-on: [self-hosted, Windows]
    steps:
      # - name: Clean Up the Previous Run
      #   run: |
      #     del /S /q .
      #   shell: cmd
      - uses: actions/checkout@v2
      - name: Build and Test
        run: |
          FOR /F "tokens=* USEBACKQ" %%F IN (`cd`) DO (set TAICHI_REPO_DIR=%%F)
          echo %TAICHI_REPO_DIR%
          set PYTHONPATH=%TAICHI_REPO_DIR%/python
          set PATH=%TAICHI_REPO_DIR%\bin;%PATH%
          echo %PATH%
          clang --version
          %PYTHON% misc/ci_setup.py ci
          mkdir build
          cd build
          cmake .. -G"Visual Studio 16 2019" -A x64 -DPYTHON_EXECUTABLE=%PYTHON% -DLLVM_DIR="C:\LLVM\taichi-llvm-10.0.0-msvc2019\lib\cmake\llvm" -DTI_WITH_CUDA=ON -DTI_WITH_OPENGL=OFF -DTI_WITH_CC=OFF
          msbuild /p:Configuration=RelWithDebInfo /p:Platform=x64 /m taichi.sln
          cd ..
          %PYTHON% -c "import taichi"
          %PYTHON% examples/laplace.py
          %PYTHON% bin/ti test -t1 -v
        shell: cmd
        env:
          PYTHON: C:\Python\Python38\python.exe
      # - name: Test
      #   run: |
      #     set TAICHI_REPO_DIR=C:\taichi
          
      #     ti diagnose
      #     ti test -vr2 -t2
      #   shell: cmd
