name: Persubmit Checks
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  code_format:
    name: Code Format
    runs-on: ubuntu-latest
    # This job will be required to pass before merging to master branch.
      - uses: actions/checkout@v2
  steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
