name: Persubmit Checks
on:
  repository_dispatch:
    types: [format-command]


# test
jobs:
  code_format:
    name: install clang-format test
    runs-on: ubuntu-latest
    # This job will be required to pass before merging to master branch.
    steps:
      - name: clone branch of PR
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GARDENER_PAT }}
          ref: ${{ github.event.client_payload.pull_request.head.ref }}
          repository: ${{ github.event.client_payload.pull_request.head.repo.full_name }}
          fetch-depth: 0
      - name: install clang-format
        run: |
          sudo apt-get install clang-format
