name: Persubmit Checks
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build_and_test_gpu:
    name: Build and Test (GPU)
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip ci') && github.event.sender.login != 'taichi-gardener' }}
    runs-on: [self-hosted, cuda]
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          git --version
          export TAICHI_REPO_DIR=`pwd`
          export PATH=/home/github/taichi-llvm/bin/:$PATH
          export CXX=clang++-8
          export PYTHON=/usr/bin/python3
          $PYTHON misc/ci_setup.py ci
        env:
          CI_SETUP_CMAKE_ARGS: -DTI_WITH_OPENGL:BOOL=ON -DTI_WITH_CC:BOOL=OFF

      - name: Test
        run: |
          export PYTHON=/usr/bin/python3
          export TAICHI_REPO_DIR=`pwd`
          export PATH=$TAICHI_REPO_DIR/bin:$PATH
          export PATH=/home/github/taichi-llvm/bin/:$PATH
          export PYTHONPATH=$TAICHI_REPO_DIR/python
          export DISPLAY=:1
          glewinfo
          $PYTHON examples/laplace.py
          ti diagnose
          ti test -vr2 -t2
