name: Presubmit Checks
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  docker_cpu_build:
    runs-on: ubuntu-latest
    container: registry.taichigraphics.com/taichidev-ubuntu20.04-test:v0.1
    steps:
      - run: |
        ti test

  docker_gpu_build:
    runs-on: [self-hosted, cuda, vulkan]
    container: registry.taichigraphics.com/taichidev-ubuntu20.04-test:v0.1
    steps:
      - run: |
        ti test
