name: Presubmit Checks
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build_and_test_windows:
    name: Build and Test (Windows)
    runs-on: windows-server2019
    timeout-minutes: 90
    steps:
      - name: Install 7Zip PowerShell
        shell: powershell
        run: Install-Module 7Zip4PowerShell -Force -Verbose

      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Download And Install Vulkan
        shell: powershell
        run: |
          Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/1.2.189.0/windows/VulkanSDK-1.2.189.0-Installer.exe" -OutFile VulkanSDK.exe
          $installer = Start-Process -FilePath VulkanSDK.exe -Wait -PassThru -ArgumentList @("/S");
          $installer.WaitForExit();

      - name: Build
        shell: powershell
        run: |
          $env:Path += ";C:/VulkanSDK/1.2.189.0/Bin"
          cd C:\
          Remove-item alias:curl
          curl --retry 10 --retry-delay 5 https://github.com/taichi-dev/taichi_assets/releases/download/llvm10/taichi-llvm-10.0.0-msvc2019.zip -LO
          7z x taichi-llvm-10.0.0-msvc2019.zip -otaichi_llvm
          curl --retry 10 --retry-delay 5 https://github.com/taichi-dev/taichi_assets/releases/download/llvm10/clang-10.0.0-win.zip -LO
          7z x clang-10.0.0-win.zip -otaichi_clang
          $env:PATH = ";C:\taichi_llvm\bin;C:\taichi_clang\bin;" + $env:PATH
          clang --version
          cd D:\a\taichi\taichi
          python -m pip install -r requirements_dev.txt
          cd python
          git fetch origin master
          $env:TAICHI_CMAKE_ARGS = $env:CI_SETUP_CMAKE_ARGS
          python build.py build
          cd ..\dist
          $env:WHL = $(dir *.whl)
          python -m pip install $env:WHL
        env:
          PYTHON: C:\hostedtoolcache\windows\Python\3.7.9\x64\python.exe
          CI_SETUP_CMAKE_ARGS: -G "Visual Studio 16 2019" -A x64 -DLLVM_DIR=C:\taichi_llvm\lib\cmake\llvm -DTI_WITH_VULKAN:BOOL=ON
          VULKAN_SDK: C:/VulkanSDK/1.2.189.0

      - name: Test
        shell: powershell
        run: |
          $env:PATH = ";C:\taichi_llvm\bin;C:\taichi_clang\bin;" + $env:PATH
          python -c "import taichi"
          python examples/algorithm/laplace.py
          python bin/taichi diagnose
          python bin/taichi changelog
          python bin/taichi test -vr2 -t2
        env:
          PYTHON: C:\hostedtoolcache\windows\Python\3.7.9\x64\python.exe

  
