name: Presubmit Checks
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:

  docker_cpu_test:
    runs-on: [self-hosted, cn, cuda, vulkan]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - run: |
          docker create --user dev --name taichi --gpus all -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix registry.taichigraphics.com/taichidev-ubuntu20.04:v0.1 /home/dev/scripts/ubuntu_build_test.sh $SHA $PY
          # docker cp ./taichi taichi:/home/dev/taichi
          docker start -a taichi
        env:
          SHA: HEAD
          PY: py38

      - name: clean docker container
        if: always()
        run: docker rm taichi -f

      ##- uses: addnab/docker-run-action@v3
      ##  with:
      ##    username: admin

          #- uses: docker://registry.taichigraphics.com/taichidev-ubuntu20.04-test:v0.1

