name: Presubmit Checks
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build_and_test_windows:
    name: Build and Test (Windows)
    runs-on: windows-latest
    steps:
      - name: Install 7Zip PowerShell
        shell: powershell
        run: Install-Module 7Zip4PowerShell -Force -Verbose

      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build
        shell: powershell
        run: |
          cd C:\
          Remove-item alias:curl
          curl --retry 10 --retry-delay 5 https://github.com/taichi-dev/taichi_assets/releases/download/llvm10/taichi-llvm-10.0.0-msvc2019.zip -LO
          7z x taichi-llvm-10.0.0-msvc2019.zip -otaichi_llvm
          curl --retry 10 --retry-delay 5 https://github.com/taichi-dev/taichi_assets/releases/download/llvm10/clang-10.0.0-win.zip -LO
          7z x clang-10.0.0-win.zip -otaichi_clang
          $env:PATH += ";C:\taichi_llvm\bin"
          $env:PATH += ";C:\taichi_clang\bin"
          clang --version
          cd D:\a\test_actions\test_actions
          python -m pip install --user numpy pybind11 gitpython
          python misc/ci_setup.py ci
          #cmake .. -G"Visual Studio 16 2019" -A x64 -DPYTHON_EXECUTABLE="$env:PYTHON" -DLLVM_DIR="C:\taichi_llvm\lib\cmake\llvm"
        env:
          PYTHON: C:\hostedtoolcache\windows\Python\3.7.9\x64\python.exe
          CI_SETUP_CMAKE_ARGS: -DLLVM_DIR=C:\taichi_llvm\lib\cmake\llvm

      - name: Test
        shell: powershell
        run: |
          $env:PATH += ";C:\taichi_llvm\bin"
          $env:PATH += ";C:\taichi_clang\bin"
          python -c "import taichi"
          python examples/algorithm/laplace.py
          python bin/taichi diagnose
          python bin/taichi test -Cvr2 -t2
        env:
          PYTHON: C:\hostedtoolcache\windows\Python\3.7.9\x64\python.exe
