name: Presubmit Checks
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:

  docker_cpu_test:
    runs-on: [self-hosted, cn, cuda, vulkan]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - run: |
          docker create --user dev --name taichi --gpus all -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix registry.taichigraphics.com/taichidev-ubuntu20.04:v0.1.0 /home/dev/taichi/.github/workflows/scripts/unix_docker_build.sh CI_SETUP_CMAKE_ARGS=$CI_SETUP_CMAKE_ARGS PY=$PY
          docker cp ./taichi taichi:/home/dev/taichi
          docker start -a taichi
        env:
          DISPLAY: :1
          CI_SETUP_CMAKE_ARGS: -DTI_WITH_OPENGL:BOOL=ON -DTI_WITH_CC:BOOL=OFF -DTI_WITH_VULKAN:BOOL=ON -DTI_BUILD_TESTS:BOOL=ON
          PY: py38

      - name: clean docker container
        if: always()
        run: docker rm taichi -f

      ##- uses: addnab/docker-run-action@v3
      ##  with:
      ##    username: admin

          #- uses: docker://registry.taichigraphics.com/taichidev-ubuntu20.04-test:v0.1

