name: Presubmit Checks
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:

  docker_cpu_test:
    runs-on: [self-hosted, cn, cuda, vulkan]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - run: |
          docker create taichidev-ubuntu20.04:v0.1 --user dev --name taichi --gpus all -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix
          docker cp ./taichi taichi:/home/dev/taichi
          docker start taichi /home/dev/scripts/ubuntu_build_test_source.sh $SHA $PY
        env:
          SHA: HEAD
          PY: py38

      ##- uses: addnab/docker-run-action@v3
      ##  with:
      ##    username: admin
      ##    password: 3550489
      ##    registry: registry.taichigraphics.com
      ##    image: registry.taichigraphics.com/taichidev-ubuntu20.04-test:v0.1
      ##    options: --user dev -it -d --name container-name --gpus all -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix name:tag /bin/bash
      ##    run: |
      ##      ti test

          #- uses: docker/login-action@v1
          #  with:
          #    registry: registry.taichigraphics.com
          #    username: admin
          #    password: 3550489

          #- uses: docker://registry.taichigraphics.com/taichidev-ubuntu20.04-test:v0.1

