name: Presubmit Checks
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  docker_cpu_build:
    runs-on: ubuntu-latest
    container: registry.taichigraphics.com/taichidev-ubuntu20.04-test:v0.1
    steps:
      - run: |
        ti test

  docker_gpu_build:
    runs-on: [self-hosted, cuda, vulkan]
    container: registry.taichigraphics.com/taichidev-ubuntu20.04-test:v0.1
    steps:
      - run: |
        ti test

  performance_monitoring:
    name: Performance monitoring (NVGPU)
    timeout-minutes: 60
    runs-on: [self-hosted, x64, cuda, linux, benchmark]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Build & Install
        run: |
          export PATH=$PATH:/usr/local/cuda/bin
          .github/workflows/scripts/unix_build.sh
        env:
          LLVM_LIB_ROOT_DIR: /opt/taichi-llvm-10.0.0
          LLVM_PATH: /opt/taichi-llvm-10.0.0/bin
          LLVM_DIR: /opt/taichi-llvm-10.0.0/lib/cmake/llvm
          CUDA_TOOLKIT_ROOT_DIR: /usr/local/cuda/
          CI_SETUP_CMAKE_ARGS: -DTI_WITH_CUDA_TOOLKIT:BOOL=ON
          BUILD_NUM_THREADS: 8
          CXX: clang++-10

      - name: Run benchmark
        run: |
          python3 benchmarks/misc/run.py /home/benchmarkbot/benchmark/