name: Test Schedule
on:
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: "*/5 * * * *"

jobs:
  test_schedule:
    name: schedule test
    runs-on: macos-latest
    steps:
      - name: test
        run: |
          echo "${{ github.event.action }}"
          echo "Triggered every 5 minites!"
          [ -z "${{ github.event.action }}" ] && export RELEASE="perform nightly release"
          [ -z "${{ github.event.action }}" ] && ls
          [ -z "${{ github.event.action }}" ] || export RELEASE="perform production release"
          [ -z "${{ github.event.action }}" ] || pwd
          echo $RELEASE

