name: Test Schedule
on:
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: "*/5 * * * *"

jobs:
  runs-on: macos
  steps:
    - name: test
      run: |
        echo "${{ github.event.action }}"
        echo "Triggered every 5 minites!"
